version: '3.8'

services:
  db:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    restart: always
    environment:
      - DEBUG=False
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  asgi:
    restart: always
    environment:
      - DEBUG=False
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  scheduler:
    restart: always
    environment:
      - DEBUG=False
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
